/**
 * agents/publisherAgent.js
 * ──────────────────────────────────────────────────────────────────────────────
 * Publisher Agent — Phase 5
 *
 * Responsibilities:
 *   1. Take the human-approved draft.
 *   2. Apply channel-specific formatting (templates).
 *   3. Save the final file to the OUTPUT_DIR.
 *   4. Update session with publishedPath.
 * ──────────────────────────────────────────────────────────────────────────────
 */

import 'dotenv/config';
import path from 'path';
import fse from 'fs-extra';
import chalk from 'chalk';
import { updateSession } from '../session.js';

export async function runPublisherAgent(session) {
  const { sessionId, approvedDraft, brief } = session;

  console.log('\n' + chalk.bold.bgGreen(' PUBLISHER AGENT ') + chalk.bold.white(' Phase 6 — Formatting & Saving'));
  console.log(chalk.dim('─'.repeat(60)));

  // Add a small delay so the user can see the "Publisher" step loading in the UI
  await new Promise(resolve => setTimeout(resolve, 2000));

  if (!approvedDraft) {
    throw new Error('[PublisherAgent] No approved draft found in session.');
  }

  const outputDir = process.env.OUTPUT_DIR || './output';
  await fse.ensureDir(outputDir);

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filename = `${brief.channel}_${sessionId}_${timestamp}.md`;
  const filePath = path.resolve(outputDir, filename);

  const finalContent = `
# ${brief.topic}
**Channel:** ${brief.channel}
**Audience:** ${brief.audience}
**Status:** Published

---

${approvedDraft}

---
Generated by AI Content Studio Pipeline
`.trim();

  await fse.writeFile(filePath, finalContent);

  console.log(chalk.green(`  💾  Published to: ${filePath}`));

  return await updateSession(sessionId, {
    publishedPath: filePath,
    currentStep: 5,
    pipelineStatus: 'done'
  });
}
