name: Secret Scan

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  gitleaks:
    name: Gitleaks Secret Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -zxvf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Gitleaks Secret Scan
        run: gitleaks detect --verbose --redact
